<a href="https://colab.research.google.com/github/chaithrashagu/Internship/blob/master/internship1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
x=2
x*7

14

In [0]:
x="Hello,I'm"
x+"python!"

"Hello,I'mpython!"

In [0]:
x=3
type(x)

int

In [0]:
x='mrudula'
type(x)

str

In [0]:
type(None)


NoneType

In [0]:
type(int)

type

In [0]:
type(type)

type

In [0]:
3


3

In [0]:
1+1

2

In [0]:
8-1

7

In [0]:
10*2



20

In [0]:
9/3



3.0

In [0]:
type(9/3)

float

In [0]:
True


True

In [0]:
True and False

False

In [0]:
True or False

True

In [0]:
2*3==5

False

In [0]:
2*3!=5

True

In [0]:
s='ARTHUR'
print(s[2])

T


In [0]:
s[-1]


'R'

In [0]:
s[1:5:2]

'RH'

In [0]:
s[:2]

'AR'

In [0]:
s[1:-1]

'RTHU'

In [0]:
s[::-1]

'RUHTRA'

In [0]:
name=input("what is your name?")

what is your name?mrudu


In [0]:
print("I'm chaithra.Nice to meet u,",name)

I'm chaithra.Nice to meet u, mrudu


In [0]:
type(print)

builtin_function_or_method

In [0]:

if the_world_is_flat:
    print("Don't fall off.")
type(the_world_is_flat)

Don't fall off.


int

In [0]:
bool(None)

False

In [0]:
bool(False)

False

In [0]:
bool(0)

False

In [0]:
data=[]
if data:
   process(data)
else:
  print("there is no data!!")

there is no data!!


Looping Statements:

In [0]:
for items in iterable:
  process(data)

In [0]:
range(3)

range(0, 3)

In [0]:
for i in range(3):
  print(i)

0
1
2


In [0]:
for i in range(10,13):
  print(i)

10
11
12


In [0]:
for i in range(2,12,3):
  print(i)

2
5
8
11


break and continue statement:


In [0]:
for i in range(10):
   if i==6:
       break
   print(i,end=',')

0,1,2,3,4,5,

In [0]:
for i in range(10):
  if i%2==0:
    print (i ,"is even")
    continue
  print(i," is odd")

0 is even
1  is odd
2 is even
3  is odd
4 is even
5  is odd
6 is even
7  is odd
8 is even
9  is odd


**FUNCTIONS**:
syntax for defining the function :
 def function name(parameter 1,parameter 2):
  #statements
  return()
  

In [108]:
#prime no generation functions
def is_prime(n):
    for i in range(2,n):
      if n%i==0:
        return False
    return True

n=input("enter the number")
for x in range(2,int(n)):
  if is_prime(x):
     print(x,"is prime")
  else:
     print(x,"is not prime")

enter the number10
2 is prime
3 is prime
4 is not prime
5 is prime
6 is not prime
7 is prime
8 is not prime
9 is not prime


SORT,MULTIPLES OF 8 in the  range of 500

In [0]:
def mul():
   for i in range(0,500):
      if i%8==0:
        print (i)
        continue
   return  
  
mul()

0
8
16
24
32
40
48
56
64
72
80
88
96
104
112
120
128
136
144
152
160
168
176
184
192
200
208
216
224
232
240
248
256
264
272
280
288
296
304
312
320
328
336
344
352
360
368
376
384
392
400
408
416
424
432
440
448
456
464
472
480
488
496


In [0]:
l=input("enter the numbers")
list=l.split()
for i in list:
    i=int(i)
list.sort() 
print('the elements in ascending order')
print(list)

enter the numbers10 2 3 2
the elements in ascending order
['10', '2', '2', '3']


In [0]:
i=input("enter the string")
value=input("value")
if value in s:
   print("found")

enter the stringmrudula is a good string
valuemrudula


In [0]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
a.shape


(3, 5)

In [0]:
a.ndim

2

In [0]:
a.dtype.name

'int64'

In [0]:
a.size

15

In [0]:
a.itemsize

8

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([6,7,8])

In [0]:
import numpy as np
a=np.arange(100).reshape(2,5,10)
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [0]:
a.ndim

3

In [0]:
a.shape

(2, 5, 10)

In [0]:
a.itemsize

8

In [0]:
import numpy as np
a=np.array([])
a

array([], dtype=float64)

In [0]:
import numpy as np
a=np.array([10,1.9,12,12.9])
a

array([10. ,  1.9, 12. , 12.9])

In [0]:
a.dtype

dtype('float64')

In [0]:
import numpy as np
a=np.array(['a',1.9,12,12.9])
a

array(['a', '1.9', '12', '12.9'], dtype='<U4')

In [0]:
a.dtype

dtype('<U4')

In [0]:
import numpy as np
a=np.array([(10,1.9,12,12.9),
           (20,13,4,5)])
a

array([[10. ,  1.9, 12. , 12.9],
       [20. , 13. ,  4. ,  5. ]])

In [0]:
import numpy as np
a=np.array([[10,1.9],[12,12.9]],dtype=complex)
a

array([[10. +0.j,  1.9+0.j],
       [12. +0.j, 12.9+0.j]])

In [0]:
import numpy as np
a=np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
import numpy as np
a=np.empty((2,5))
a

array([[2.25477727e-316, 2.35541533e-312, 2.46151512e-312,
        2.33419537e-312, 2.31297541e-312],
       [2.56761491e-312, 2.05833592e-312, 6.79038654e-313,
        2.37663529e-312, 9.23854182e-315]])

In [0]:
a.dtype

dtype('float64')

**CREATING THE ARRAY WITH ELEMENTS VALUES 1 BY USING ONES() FUNCTION**

In [0]:
import numpy as np
a=np.ones((2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
a.dtype

dtype('float64')

**CREATING AN MULTIDIMENSIONAL ARRAY USING RANGE() FUNCTION**

In [0]:
import numpy as np
a=np.arange(4,30,2)
a

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [0]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

***CREATING THE ARRAY WITH THE LINSPACE() FUNCTION ***

In [0]:

from numpy import pi
np.linspace(0,2,9)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
from numpy import pi
np.linspace(0,2,9)
x = np.linspace( 0, 2*pi, 100 )       
f = np.sin(x)

**printing the values of one, multidimensional array**

In [0]:
import numpy as np
a=np.arange(10,30,2)
print(a)

[10 12 14 16 18 20 22 24 26 28]


In [0]:
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [0]:
a=np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


**printing only the corners of the matrix**

In [0]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [0]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


**basic operations**

**performing addition and subtraction**

In [0]:
a=np.array([20,3,9,8,5])
b=np.arange(5)
b
c=a-b
print(c)
c=a+b
print(c)

[20  2  7  5  1]
[20  4 11 11  9]


**performing multiplication**

In [0]:
a=np.array([20,3,9,8,5])
b=np.arange(5)
print(b)
c=a*2
print(c)

[ 0  1  4  9 16]


In [0]:
10*np.sin(a)

array([ 9.12945251,  1.41120008,  4.12118485,  9.89358247, -9.58924275])

**performing exponential operation** 

In [0]:
print(b**2)

[ 0  1  4  9 16]


**checking whether the values of array lies < or > than value**

In [0]:
print(a)
a>35

[20  3  9  8  5]


array([False, False, False, False, False])

**multiplication of matrix element by element using * operator**

In [0]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
a*b


array([[2, 0],
       [0, 4]])

**muliplication of matrix by using ". and @ " operator**

In [0]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
a@b

array([[5, 4],
       [3, 4]])

In [0]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
a.dot(b)

array([[5, 4],
       [3, 4]])

In [0]:
a=np.array([[1,1],[0,1],[1,9]])
b=np.array([[2,0,4],[3,4,4]])
a@b

array([[ 5,  4,  8],
       [ 3,  4,  4],
       [29, 36, 40]])

**multiplication of three dimensional array with multiplying one matrix of a with  one matrix of  b**

In [0]:
a=np.arange(12).reshape(2,3,2)
print(a)
b=np.arange(12).reshape(2,2,3)
print(b)
a@b

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([[[  3,   4,   5],
        [  9,  14,  19],
        [ 15,  24,  33]],

       [[ 99, 112, 125],
        [129, 146, 163],
        [159, 180, 201]]])

**to create array using random function**

In [0]:
a = np.random.random((2,3))
a

array([[0.13352689, 0.93844788, 0.75354033],
       [0.26405458, 0.32596441, 0.63183354]])

**operations performed on matrix**

In [0]:
a.sum()

3.047367624743318

In [0]:
a.max()

0.9384478811182736

In [0]:
a.min()

0.13352688501266086

In [0]:
b=np.arange(12).reshape(3,4)
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**printing the sum of columns by providing axis=0 and sum of individual rows by prividing axis=1**

In [0]:
b.sum(axis=1)

array([ 6, 22, 38])

In [0]:
b.sum(axis=0)

array([12, 15, 18, 21])

**Printing the minimum element of each row and each column by using the function min(axis=0 for column and axis=1 for row)**

In [0]:
b.min(axis=1)

array([0, 4, 8])

**printing the values of each row by adding one element with other element in same row with axis=1 same for colo=umn by providing axes=0**

In [0]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [0]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

**universal functions**

In [0]:
import numpy as np
b=np.arange(3)
b

array([0, 1, 2])

**finding the power of e with respect to the values of matrix i.e e=2.71828183**

In [0]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [0]:
a=np.array([10,20,30])
np.add(a,b)

array([10, 21, 32])

In [0]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [0]:
a=np.arange(10).reshape(5,2)
print(a)
b=np.arange(10).reshape(5,2)
print(b)
np.exp(a)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03]])

In [0]:
np.add(a,b)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

**indexing and slicing **

In [0]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
print(a[2])

8


In [0]:
a[1:5]

array([ 1,  8, 27, 64])

In [0]:
a[:6:2]=-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [0]:
a[3:1:-1]

array([   27, -1000])

In [0]:
a[2]=16
a

array([-1000,     1,    16,    27, -1000,   125,   216,   343,   512,
         729])

In [0]:
a=np.arange(10).reshape(5,2)**2
print(a)



[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]]


In [0]:
a[2]

array([16, 25])

In [0]:
a[:2:-1]

array([[64, 81],
       [36, 49]])

In [0]:
a=np.arange(20).reshape(2,5,2)**2
print(a)

[[[  0   1]
  [  4   9]
  [ 16  25]
  [ 36  49]
  [ 64  81]]

 [[100 121]
  [144 169]
  [196 225]
  [256 289]
  [324 361]]]


In [0]:
a[0,4]

array([64, 81])

**slicing the third dimensional array by specifying[matrix(:),row(:),columnn(:)]**

In [0]:
a[:2,1:,:1]

array([[[  4],
        [ 16],
        [ 36],
        [ 64]],

       [[144],
        [196],
        [256],
        [324]]])

In [0]:

print(a)
print("\n",a[0,3,0])
print("\n",a[:1,2:4,:1])

[[[  0   1]
  [  4   9]
  [ 16  25]
  [ 36  49]
  [ 64  81]]

 [[100 121]
  [144 169]
  [196 225]
  [256 289]
  [324 361]]]

 36

 [[[16]
  [36]]]


In [0]:
a=np.array(['a','chai','v','d'])
a


array(['a', 'chai', 'v', 'd'], dtype='<U4')

In [0]:
a[1]

'chai'

In [0]:
a[:2]

array(['a', 'chai'], dtype='<U4')

**printing the values by using the dot(.) operator**

In [0]:
a=np.array([[10,20,30],
          [35,25,67]])
a


array([[10, 20, 30],
       [35, 25, 67]])

In [0]:
print(a[0,...])#printing the first row of the array 
a[1,...]

[10 20 30]


array([35, 25, 67])

**iteration to display the each rrow through each iteration**

In [0]:
for row in a:
  print(row)

[10 20 30]
[35 25 67]


**to retrieve the each element by using the flat attribute which is an iterator**

In [0]:
for element in a.flat:
  print(element)

10
20
30
35
25
67


**shape manipulation**

In [0]:
 a = np.floor(20*np.random.random((3,4)))
 a

array([[ 4., 12.,  6.,  1.],
       [14.,  3., 19.,  8.],
       [ 7., 16., 15., 16.]])

In [0]:
a.shape

(3, 4)

**ravel() is used to get the matrix elements in 1D array.i.e flattened array**

In [0]:
a.ravel()

array([ 4., 12.,  6.,  1., 14.,  3., 19.,  8.,  7., 16., 15., 16.])

reshape() will return the matrix with the modified dimension

In [0]:
a.reshape(2,6)


array([[ 4., 12.,  6.,  1., 14.,  3.],
       [19.,  8.,  7., 16., 15., 16.]])

In [0]:
a

array([[ 4., 12.,  6.,  1.],
       [14.,  3., 19.,  8.],
       [ 7., 16., 15., 16.]])

**T returns the transpose of matrix i.e m*n=>n*m**

In [0]:
a.T

array([[ 4., 14.,  7.],
       [12.,  3., 16.],
       [ 6., 19., 15.],
       [ 1.,  8., 16.]])

In [0]:
a.shape

(3, 4)

In [0]:
a.T.shape

(4, 3)

**resize() wil alter the dimensions of the matrix **

In [0]:
a.resize(2,6)
a

array([[ 4., 12.,  6.,  1., 14.,  3.],
       [19.,  8.,  7., 16., 15., 16.]])

In [0]:
a.shape

(2, 6)

In [3]:
import numpy as np
a = np.floor(10*np.random.random((2,2)))
a

array([[4., 7.],
       [3., 3.]])

In [4]:
b= np.floor(10*np.random.random((2,2)))
b

array([[3., 1.],
       [1., 1.]])

In [0]:
np.vstack((a,b))

array([[6., 9.],
       [2., 0.],
       [3., 4.],
       [9., 9.]])

In [0]:
np.hstack((a,b))

array([[6., 9., 3., 4.],
       [2., 0., 9., 9.]])

In [0]:
np.column_stack((a,b))

array([[6., 9., 3., 4.],
       [2., 0., 9., 9.]])

In [6]:
import numpy as np
from numpy import newaxis
np.column_stack((a,b))

array([[4., 7., 3., 1.],
       [3., 3., 1., 1.]])

In [8]:
np.hstack((a,b))

array([[4., 7., 3., 1.],
       [3., 3., 1., 1.]])

In [9]:
 a[:,newaxis]

array([[[4., 7.]],

       [[3., 3.]]])

In [10]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[[4., 7.],
        [3., 1.]],

       [[3., 3.],
        [1., 1.]]])

In [11]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[[4., 7.],
        [3., 1.]],

       [[3., 3.],
        [1., 1.]]])

copy

In [13]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
b=a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
b is a

True

In [18]:
b.shape=2,6
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [20]:
c=a.view()
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:
c is a

False

In [22]:
c.base is a

True

In [25]:
d=a.copy()
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [26]:
d is a

False

In [27]:
d.base is a

False

In [28]:
d.shape=3,4
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

 **LINEAR ALGEBRA**

In [36]:
a=np.array([[10,20,30],[4,5,7],[2,3,4]])
a

array([[10, 20, 30],
       [ 4,  5,  7],
       [ 2,  3,  4]])

In [37]:
a.transpose()

array([[10,  4,  2],
       [20,  5,  3],
       [30,  7,  4]])

In [40]:
print(a)
np.linalg.inv(a)

[[10 20 30]
 [ 4  5  7]
 [ 2  3  4]]


array([[-0.1,  1. , -1. ],
       [-0.2, -2. ,  5. ],
       [ 0.2,  1. , -3. ]])

In [44]:
a=np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [45]:
np.linalg.inv(a)

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

**eye() is a function which will return the  identity matrix where identity matrix is represented by  1's in diagonal and 0 for non diagonal elements**

In [50]:
u=np.eye(3,dtype=int)
u

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**FINDING THE PRODUCT OF MATRIX**

In [55]:
j=np.array([[1,-1],[0,1]])
j

array([[ 1, -1],
       [ 0,  1]])

In [56]:
j@j

array([[ 1, -2],
       [ 0,  1]])

In [57]:
np.trace(u)

3

**solving the equation throgh matrix**

In [60]:
y=np.array([[5],[7]])
y

array([[5],
       [7]])

In [62]:
print(a)
np.linalg.solve(a,y)

[[10 20]
 [30 40]]


array([[-0.3],
       [ 0.4]])

In [64]:
print(j)
np.linalg.eig(j)

[[ 1 -1]
 [ 0  1]]


(array([1., 1.]), array([[1.00000000e+00, 1.00000000e+00],
        [0.00000000e+00, 2.22044605e-16]]))

**ARRAY EXAMPLES**

In [67]:
#declaraation of the array by importing the array module
#syntax for declaring the arrayvariable arrayidentifying_variable=array(typecode, [Initializers])
from array import *
my_array=array('i',[1,2,3,4,5])
my_array

array('i', [1, 2, 3, 4, 5])

In [69]:
from array import *
my_array=array('i',[1,2,3,4,5])
for i in my_array:
  print(i)

1
2
3
4
5


**accessing the individual  element of array**

In [70]:
my_array[2]

3

**appending the element to the array using the append() method**

In [76]:
my_array.append(6)
my_array

array('i', [1, 2, 3, 4, 5, 6, 6, 6])

**inserting the value to the array using insert(index,value) method **

In [78]:
my_array.insert(6,7)
my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 7, 6, 6])

**more than one value can be appended by using the extend() method**

In [80]:
a=array('i',[8,9,10])
my_array.extend(a)
my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 7, 6, 6, 8, 9, 10])

**add items from list to array using fromlist()**

In [81]:
c=[11,12,13]
my_array.fromlist(c)
my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 7, 6, 6, 8, 9, 10, 11, 12, 13])

**remove the elemnts from the array using the method remove()**

In [83]:
my_array.remove(6)
my_array

array('i', [1, 2, 3, 4, 5, 7, 7, 6, 8, 9, 10, 11, 12, 13])

In [85]:
my_array.remove(7)
my_array

array('i', [1, 2, 3, 4, 5, 7, 6, 8, 9, 10, 11, 12, 13])

**remove the last element from the array using the pop() method**

In [86]:
my_array.pop()

13

**fetching the element from array using index method**

In [92]:
print(my_array)
my_array.index(5)

array('i', [1, 2, 3, 4, 5, 7, 6, 8, 9, 10, 11, 12])


4

**reverse of the array using the reverse() method**

In [95]:
my_array.reverse()
my_array

array('i', [12, 11, 10, 9, 8, 6, 7, 5, 4, 3, 2, 1])

In [96]:
my_array.buffer_info()

(140033923469080, 12)

In [99]:
my_array.count(6)

1

In [104]:
my_char_array = array('b', [ord('g'),ord('e'),ord('e'),ord('k')])
my_char_array


array('b', [103, 101, 101, 107])

In [106]:
c=my_array.tolist()
c

[12, 11, 10, 9, 8, 6, 7, 5, 4, 3, 2, 1]

In [107]:
my_char_array.fromstring("stuff")
my_char_array

array('b', [103, 101, 101, 107, 115, 116, 117, 102, 102])

# **Functions**
**function to generate the  prime  numbers**

In [119]:

def is_prime(n):
    for i in range(2,n):
      if n%i==0:
        return False
    return True

n=input("enter the number")
for x in range(2,int(n)):
  if is_prime(x):
     print(x,"is prime")
  else:
     print(x,"is not prime")

enter the number10
2 is prime
3 is prime
4 is not prime
5 is prime
6 is not prime
7 is prime
8 is not prime
9 is not prime


In [178]:
def is_prime(n):
  for i in range(2,n):
    if (n%i)==0 :
      return True
    else:
      return False
  
n=int(input("enter the number")) 
if is_prime(n):
  print("x is not prime")
else:
  print("x is prime")

enter the number15
x is prime


In [181]:
def even(n):
  for i in range(0,n):
    if(i%2)==0:
      print(i)
    continue
  return    
n=int(input("enter the last element"))
even(n)

enter the last element101
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [221]:
from array import *

n=int(input("n"))
arr=array('i',[])
for i in range(0,n):
  ele=int(input(("take element")))
  arr.append(ele)
for i in range(0,n):
  for j in range(0,n-1):
    if arr[i]<(arr[j+1]+1):
      print(arr[i])
      break
    else:
      continue
    
      

n5
take element1
take element2
take element3
take element4
take element1
1
2
3
4
1
