<a href="https://colab.research.google.com/github/chaithrashagu/Internship/blob/master/internship1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
x=2
x*7

14

In [0]:
x="Hello,I'm"
x+"python!"

"Hello,I'mpython!"

In [0]:
x=3
type(x)

int

In [0]:
x='mrudula'
type(x)

str

In [0]:
type(None)


NoneType

In [0]:
type(int)

type

In [0]:
type(type)

type

In [0]:
3


3

In [0]:
1+1

2

In [0]:
8-1

7

In [0]:
10*2



20

In [0]:
9/3



3.0

In [0]:
type(9/3)

float

In [0]:
True


True

In [0]:
True and False

False

In [0]:
True or False

True

In [0]:
2*3==5

False

In [0]:
2*3!=5

True

In [0]:
s='ARTHUR'
print(s[2])

T


In [0]:
s[-1]


'R'

In [0]:
s[1:5:2]

'RH'

In [0]:
s[:2]

'AR'

In [0]:
s[1:-1]

'RTHU'

In [0]:
s[::-1]

'RUHTRA'

In [0]:
name=input("what is your name?")

what is your name?mrudu


In [0]:
print("I'm chaithra.Nice to meet u,",name)

I'm chaithra.Nice to meet u, mrudu


In [0]:
type(print)

builtin_function_or_method

In [0]:

if the_world_is_flat:
    print("Don't fall off.")
type(the_world_is_flat)

Don't fall off.


int

In [0]:
bool(None)

False

In [0]:
bool(False)

False

In [0]:
bool(0)

False

In [0]:
data=[]
if data:
   process(data)
else:
  print("there is no data!!")

there is no data!!


Looping Statements:

In [0]:
for items in iterable:
  process(data)

In [0]:
range(3)

range(0, 3)

In [0]:
for i in range(3):
  print(i)

0
1
2


In [0]:
for i in range(10,13):
  print(i)

10
11
12


In [0]:
for i in range(2,12,3):
  print(i)

2
5
8
11


break and continue statement:


In [0]:
for i in range(10):
   if i==6:
       break
   print(i,end=',')

0,1,2,3,4,5,

In [0]:
for i in range(10):
  if i%2==0:
    print (i ,"is even")
    continue
  print(i," is odd")

0 is even
1  is odd
2 is even
3  is odd
4 is even
5  is odd
6 is even
7  is odd
8 is even
9  is odd


**FUNCTIONS**:
syntax for defining the function :
 def function name(parameter 1,parameter 2):
  #statements
  return()
  

In [0]:
#prime no generation functions
def is_prime(n):
    for i in range(2,n):
      if n%i==0:
        return False
    return True

n=input("enter the number")
for x in range(2,int(n)):
  if is_prime(x):
     print(x,"is prime")
  else:
     print(x,"is not prime")

enter the number4
2 is prime
3 is prime


SORT,MULTIPLES OF 8 in the  range of 500

In [0]:
def mul():
   for i in range(0,500):
      if i%8==0:
        print (i)
        continue
   return  
  
mul()

0
8
16
24
32
40
48
56
64
72
80
88
96
104
112
120
128
136
144
152
160
168
176
184
192
200
208
216
224
232
240
248
256
264
272
280
288
296
304
312
320
328
336
344
352
360
368
376
384
392
400
408
416
424
432
440
448
456
464
472
480
488
496


In [0]:
l=input("enter the numbers")
list=l.split()
for i in list:
    i=int(i)
list.sort() 
print('the elements in ascending order')
print(list)

enter the numbers10 2 3 2
the elements in ascending order
['10', '2', '2', '3']


In [0]:
i=input("enter the string")
value=input("value")
if value in s:
   print("found")

enter the stringmrudula is a good string
valuemrudula


In [1]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape


(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int64'

In [5]:
a.size

15

In [7]:
a.itemsize

8

In [8]:
type(a)

numpy.ndarray

In [0]:
b=np.array([6,7,8])

In [19]:
import numpy as np
a=np.arange(100).reshape(2,5,10)
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [20]:
a.ndim

3

In [21]:
a.shape

(2, 5, 10)

In [22]:
a.itemsize

8

In [26]:
import numpy as np
a=np.array([])
a

array([], dtype=float64)

In [27]:
import numpy as np
a=np.array([10,1.9,12,12.9])
a

array([10. ,  1.9, 12. , 12.9])

In [28]:
a.dtype

dtype('float64')

In [29]:
import numpy as np
a=np.array(['a',1.9,12,12.9])
a

array(['a', '1.9', '12', '12.9'], dtype='<U4')

In [31]:
a.dtype

dtype('<U4')

In [35]:
import numpy as np
a=np.array([(10,1.9,12,12.9),
           (20,13,4,5)])
a

array([[10. ,  1.9, 12. , 12.9],
       [20. , 13. ,  4. ,  5. ]])

In [38]:
import numpy as np
a=np.array([[10,1.9],[12,12.9]],dtype=complex)
a

array([[10. +0.j,  1.9+0.j],
       [12. +0.j, 12.9+0.j]])

In [39]:
import numpy as np
a=np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
import numpy as np
a=np.empty((2,5))
a

array([[2.25477727e-316, 2.35541533e-312, 2.46151512e-312,
        2.33419537e-312, 2.31297541e-312],
       [2.56761491e-312, 2.05833592e-312, 6.79038654e-313,
        2.37663529e-312, 9.23854182e-315]])

In [45]:
a.dtype

dtype('float64')

**CREATING THE ARRAY WITH ELEMENTS VALUES 1 BY USING ONES() FUNCTION**

In [42]:
import numpy as np
a=np.ones((2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
a.dtype

dtype('float64')

**CREATING AN MULTIDIMENSIONAL ARRAY USING RANGE() FUNCTION**

In [48]:
import numpy as np
a=np.arange(4,30,2)
a

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [52]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

**CREATING THE ARRAY WITH THE LINSPACE() FUNCTION **

In [51]:

from numpy import pi
np.linspace(0,2,9)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
from numpy import pi
np.linspace(0,2,9)
x = np.linspace( 0, 2*pi, 100 )       
f = np.sin(x)

**printing the values of one, multidimensional array**

In [63]:
import numpy as np
a=np.arange(10,30,2)
print(a)

[10 12 14 16 18 20 22 24 26 28]


In [65]:
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [68]:
a=np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


**printing only the corners of the matrix**

In [72]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [73]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


**basic operations**

**performing addition and subtraction**

In [86]:
a=np.array([20,3,9,8,5])
b=np.arange(5)
b
c=a-b
print(c)
c=a+b
print(c)

[20  2  7  5  1]
[20  4 11 11  9]


**performing multiplication**

In [95]:
a=np.array([20,3,9,8,5])
b=np.arange(5)
print(b)
c=a*2
print(c)

[ 0  1  4  9 16]


In [89]:
10*np.sin(a)

array([ 9.12945251,  1.41120008,  4.12118485,  9.89358247, -9.58924275])

**performing exponential operation** 

In [90]:
print(b**2)

[ 0  1  4  9 16]


**checking whether the values of array lies < or > than value**

In [99]:
print(a)
a>35

[20  3  9  8  5]


array([False, False, False, False, False])

**multiplication of matrix element by element using * operator**

In [100]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
a*b


array([[2, 0],
       [0, 4]])

**muliplication of matrix by using ". and @ " operator**

In [102]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
a@b

array([[5, 4],
       [3, 4]])

In [105]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
a.dot(b)

array([[5, 4],
       [3, 4]])

In [108]:
a=np.array([[1,1],[0,1],[1,9]])
b=np.array([[2,0,4],[3,4,4]])
a@b

array([[ 5,  4,  8],
       [ 3,  4,  4],
       [29, 36, 40]])

**multiplication of three dimensional array with multiplying one matrix of a with  one matrix of  b**

In [110]:
a=np.arange(12).reshape(2,3,2)
print(a)
b=np.arange(12).reshape(2,2,3)
print(b)
a@b

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([[[  3,   4,   5],
        [  9,  14,  19],
        [ 15,  24,  33]],

       [[ 99, 112, 125],
        [129, 146, 163],
        [159, 180, 201]]])

**to create array using random function**

In [112]:
a = np.random.random((2,3))
a

array([[0.13352689, 0.93844788, 0.75354033],
       [0.26405458, 0.32596441, 0.63183354]])

**operations performed on matrix**

In [114]:
a.sum()

3.047367624743318

In [116]:
a.max()

0.9384478811182736

In [117]:
a.min()

0.13352688501266086

In [121]:
b=np.arange(12).reshape(3,4)
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**printing the sum of columns by providing axis=0 and sum of individual rows by prividing axis=1**

In [124]:
b.sum(axis=1)

array([ 6, 22, 38])

In [125]:
b.sum(axis=0)

array([12, 15, 18, 21])

**Printing the minimum element of each row and each column by using the function min(axis=0 for column and axis=1 for row)**

In [127]:
b.min(axis=1)

array([0, 4, 8])

**printing the values of each row by adding one element with other element in same row with axis=1 same for colo=umn by providing axes=0**

In [131]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [132]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])