<a href="https://colab.research.google.com/github/chaithrashagu/Internship/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

**Pandas series object**

In [0]:
data=pd.Series([0.1,0.3,1.4,1.5]) 
data

0    0.1
1    0.3
2    1.4
3    1.5
dtype: float64

In [0]:
data.values#same as the numpy array]

array([0.1, 0.3, 1.4, 1.5])

In [0]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [0]:
data[1]#accessing the data elements in the series

0.3

In [0]:
data[1:3]#Accessing the elements within the range 1 and 3-1

1    0.3
2    1.4
dtype: float64

In [0]:
data=pd.Series([0.25,3.25,5.4,23],index=['a','b','c','d'])#index can be specified explicitly it can be integers and the characters 
data

a     0.25
b     3.25
c     5.40
d    23.00
dtype: float64

In [0]:
data[2]

5.4

In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],# index can either be sequential or the non sequential
                 index=[2, 5, 'a', 7])
data

2    0.25
5    0.50
a    0.75
7    1.00
dtype: float64

In [0]:
data['a']

0.75

**series as specialized dictionary**

In [0]:
fish_count={'golden_fish':1224325,
           'tiger_fish':3465348,
           'shark':2435,
           'dolphin':6596}
print(fish_count)
fish=pd.Series(fish_count)
fish

{'golden_fish': 1224325, 'tiger_fish': 3465348, 'shark': 2435, 'dolphin': 6596}


golden_fish    1224325
tiger_fish     3465348
shark             2435
dolphin           6596
dtype: int64

In [0]:
fish['shark']

2435

**constructing the series objects
syntax=pd.Series(dat,,index=index)**

In [0]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [0]:
pd.Series({2:'v',6:'r',1:'p'})

2    v
6    r
1    p
dtype: object

In [0]:
pd.Series(5,index=[10,20,30])

10    5
20    5
30    5
dtype: int64

In [0]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [0]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

# **Data frames**

In [0]:
maxfishes_dict={'golden_fish':1245,'tiger_fish':1245456,'shark':58768,'dolphin':32753}

place=pd.Series(maxfishes_dict)
place


golden_fish       1245
tiger_fish     1245456
shark            58768
dolphin          32753
dtype: int64

In [0]:
fishes=pd.DataFrame({'max_fishes':place,'fish':fish})
fishes

max_fishes     fish
golden_fish        1245  1224325
tiger_fish      1245456  3465348
shark             58768     2435
dolphin           32753     6596

In [0]:
fishes.index

Index(['golden_fish', 'tiger_fish', 'shark', 'dolphin'], dtype='object')

In [0]:
fishes.columns

Index(['max_fishes', 'fish'], dtype='object')

In [0]:
fishes['fish']

golden_fish    1224325
tiger_fish     3465348
shark             2435
dolphin           6596
Name: fish, dtype: int64

**constructing the data  frame objects**

In [0]:
#from a single series objects
pd.DataFrame(fishes,columns=['max_fishes'])#syntax=pd.DataFrame(DataFarame_name,columns=['column_name'])

max_fishes
golden_fish        1245
tiger_fish      1245456
shark             58768
dolphin           32753

In [0]:
#From a list of dicts
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [0]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

**From a two-dimensional NumPy array**

In [0]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.939469  0.372757
b  0.753000  0.766466
c  0.548622  0.190226

In [0]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [0]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

**The Pandas Index Object**

In [0]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [0]:
ind[1] = 0

TypeError: ignored

In [0]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [75]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [76]:
indA | indB 

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [79]:
indB ^ indA

Int64Index([1, 2, 9, 11], dtype='int64')

# **Data selection and indexing**

In [80]:
#Series as dictionary
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [81]:
data['b']

0.5

In [82]:
'a' in data

True

In [83]:
data.keys()# display the key of dictionary

Index(['a', 'b', 'c', 'd'], dtype='object')

In [84]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

**Series as one-dimensional array**

In [85]:
data['a':'c']#slicing using external specified index

a    0.25
b    0.50
c    0.75
dtype: float64

In [88]:
data[0:2]#slicing the series using the implicit integer index

0.25

In [89]:
data[(data > 0.3) & (data < 0.8)]#masking

b    0.50
c    0.75
dtype: float64

In [93]:
data[['a', 'd']]#fancy indexing-specified index value will be retrived

a    0.25
d    1.00
dtype: float64

# **Indexers: loc, iloc, and ix**

In [94]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [95]:
# explicit index when indexing
data[1]

'a'

In [97]:
# implicit index when slicing,it will take index as [0,1,2]
data[1:2]

3    b
dtype: object

In [100]:
data.loc[3]#loc will take the index value we choosed explicitly

'b'

In [107]:
data.loc[:5]

1    a
3    b
5    c
dtype: object

In [108]:
data.loc[1:3]#iloc attribute will take the implicit  indedx of the values

1    a
3    b
dtype: object

In [109]:
data.iloc[1:3]

3    b
5    c
dtype: object

# **Data Selection in DataFrame**

In [111]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [112]:
data['area']#specifying the col name off data frame

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [113]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [114]:
data.area is data['area']

True

In [115]:
data.pop is data['pop']

False

In [116]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

# **DataFrame as two-dimensional array**

In [117]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

# ** transpose the full DataFrame to swap rows and columns:**

In [118]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [119]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [120]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [121]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [122]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [123]:
data.ix[:3, :'pop']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [124]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [125]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [126]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [127]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

# **Ufuncs: Index Preservation**

In [128]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [129]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [130]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [131]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

**UFuncs: Index Alignment**

In [0]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [133]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [134]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [135]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])#the missed index will be replaced with nan in result
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [136]:
A.add(B, fill_value=0)#fill themissed index value with the 0

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

Index alignment in DataFrame

In [137]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [141]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  4  8  6
1  1  3  8
2  1  9  8

In [142]:
A + B

A     B   C
0  9.0  15.0 NaN
1  8.0   2.0 NaN
2  NaN   NaN NaN

In [143]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   9.0  15.0  10.5
1   8.0   2.0  12.5
2  13.5   5.5  12.5

Ufuncs: Operations Between DataFrame and Series

In [144]:
A = rng.randint(10, size=(3, 4))
A

array([[9, 4, 1, 3],
       [6, 7, 2, 0],
       [3, 1, 7, 3]])

In [145]:
A - A[0]#substracting the elemnts of elements in A with 0th row of matrix A

array([[ 0,  0,  0,  0],
       [-3,  3,  1, -3],
       [-6, -3,  6,  0]])

In [146]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]#assigning the value 0 for elements of 0th row

Q  R  S  T
0  0  0  0  0
1 -3  3  1 -3
2 -6 -3  6  0

In [147]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  5  0 -3 -1
1 -1  0 -5 -7
2  2  0  6  2

In [148]:
halfrow = df.iloc[0, ::2]
halfrow

Q    9
S    1
Name: 0, dtype: int64

In [149]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -3.0 NaN  1.0 NaN
2 -6.0 NaN  6.0 NaN

**handling missing data**

In [150]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [151]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
10 loops, best of 3: 79.9 ms per loop

dtype = int
100 loops, best of 3: 2.22 ms per loop



Missing numerical data¶

In [154]:
vals2 = np.array([1, np.nan, 3, 4]) 
print(vals2)
vals2.dtype

[ 1. nan  3.  4.]


dtype('float64')

In [157]:
1 + np.nan#NaN is a bit like a data virus–it infects any other object it touches

nan

In [156]:
0 *  np.nan

nan

In [158]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [159]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)#NumPy does provide some special aggregations that will ignore these missing values:

(8.0, 1.0, 4.0)

In [160]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [0]:
#detecting null values
data = pd.Series([1, np.nan, 'hello', None])

In [162]:
data.isnull()#to check whether the value is null or not

0    False
1     True
2    False
3     True
dtype: bool

In [163]:
data[data.notnull()]#displays the data that is not null

0        1
2    hello
dtype: object

Dropping null values

In [164]:
data.dropna()

0        1
2    hello
dtype: object

In [165]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [166]:
df.dropna()#remove the rows snd columns where the value is nan

0    1  2
1  2.0  3.0  5

In [167]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [168]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [169]:
df.dropna(axis='columns', how='all')#removing the columns where all the values is nan

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [0]:
#For finer-grained control, the thresh parameter lets you specify a minimum number of non-null values for the row/column to be kept:

In [170]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN